load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "app",
    srcs = ["example/Main.java"],
    main_class = "example.Main",
    visibility = ["//visibility:public"],
    deps = [
        "//lib",
        "//vendor:selenium",
    ] + select({
        "//:guava_23": ["//vendor:guava23"],
        "//conditions:default": ["//vendor:guava22"],
    }),
)
